micronaut:
  application:
    name: orchestratorManager
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
datasources:
  default:
    url: ${O2_DATASOURCE_URL}
    username: ${O2_DATASOURCE_USER}
    password: ${O2_DATASOURCE_PASS}
    driverClassName: ${O2_DATASOURCE_DRIVER_NAME}
    dialect: ${O2_DATASOURCE_DIALECT}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: ${O2_SHOW_SQL:false}
netty:
  default:
    allocator:
      max-order: 3
flyway:
  enabled: ${O2_FLYWAY_ENABLED:true}
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      locations:
        - classpath:db/migration/postgres
